#!/usr/local/bin/bash
connect(){
socat  pty,link=/dev/cuaU0,raw,user="YOUR LOCAL USER",group=dialer,mode=777 tcp:SOURCEIP:SOURCE PORT|| connect
}
connect
### You have any *nix machine with special usb connect - anything storage or even cellphone !- 
### @ the other side meanse source ip you have a listened ser2net forwarding your usb....
### @ this side you are running FBSD and have acess to that USB.
### mode/perm is in your hand. ;)
